In [36]:
import pandas as pd
import json
import requests
import geopandas as gpd

communes_littorales = gpd.read_file("../data/communes_littorales/communes_littorales.shp")
communes_littorales['INSEE_COM'] = communes_littorales['INSEE_COM'].astype(str).str.zfill(5)

comm_list = communes_littorales['INSEE_COM'].tolist()[300:400]
print(len(comm_list), "communes littorales")



# Construction de l'URL avec toutes les communes de comm_list
geo_params = "&".join([f"GEO=COM-{code}" for code in comm_list])
api_url = f"https://api.insee.fr/melodi/V2/data/DS_FILOSOFI_CC?{geo_params}&FILOSOFI_MEASURE=IR_D9_D1_SL"


get_data = requests.get(api_url, verify= False)
data_from_net = get_data.content
data = json.loads(data_from_net)

# Extraction des informations du jeu de données
title = data['title']['fr']
identifier = data['identifier']

#Extraction des observations du jeu de données filtré, sur lesquelles on va boucler
observations = data['observations']
extracted_data = []

#Boucle de lecture des observations dans le json 
for obs in observations:
    dimensions = obs['dimensions']
    
    # Suivant les jeux de données attributes est présent ou non
    if 'attributes' in obs:
        attributes = obs['attributes']
    else:
        attributes = None

    # Suivant les jeux de données value peut être absent
    if 'value' in obs['measures']['OBS_VALUE_NIVEAU']:
        measures = obs['measures']['OBS_VALUE_NIVEAU']['value']
    else:
        mesures = None
    
    # on rassemble tout dans un objet
    if 'attributes' in obs:
        combined_data = {**dimensions,**attributes, 'OBS_VALUE_NIVEAU': measures}
    else:
        combined_data = {**dimensions, 'OBS_VALUE_NIVEAU': measures}
    
    extracted_data.append(combined_data)

#Création d'un dataframe python
df = pd.DataFrame(extracted_data)

print(f'Jeu de données : {identifier} \nTitre : {title} ')
print(df)

100 communes littorales

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

,ID,STATUT,INSEE_COM,NOM_COM,INSEE_ARR,NOM_DEP,INSEE_DEP,NOM_REG,INSEE_REG,CODE_EPCI,NOM_COM_M,POPULATION,geometry
0,BDCSURCO0000000009597579,Commune simple,56084,Le Hzo,3,MORBIHAN,56,BRETAGNE,53,200067932,LE HEZO,778,"MULTIPOLYGON (((273116 6736441, 273031 6736347..."
1,BDCSURCO0000000009596923,Commune simple,56262,Bono,3,MORBIHAN,56,BRETAGNE,53,200067932,BONO,2113,"POLYGON ((254608 6741738, 254603 6741763, 2545..."
2,BDCSURCO0000000009596932,Commune simple,56069,Groix,1,MORBIHAN,56,BRETAGNE,53,200042174,GROIX,2247,"POLYGON ((218163 6744006, 218123 6744006, 2180..."
3,BDCSURCO0000000009597578,Commune simple,56248,Surzur,3,MORBIHAN,56,BRETAGNE,53,200067932,SURZUR,4128,"POLYGON ((272425 6733779, 272476 6733883, 2725..."
4,BDCSURCO0000000009597261,Prfecture,56260,Vannes,3,MORBIHAN,56,BRETAGNE,53,200067932,VANNES,53036,"POLYGON ((263884 6744530, 263925 6744725, 2639..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
924,BDCSURCO0000000009610800,Commune simple,40108,Gastes,2,LANDES,40,NOUVELLE-AQUITAINE,75,244000873,GASTES,684,"POLYGON ((358733 6365771, 358786 6365998, 3587..."
925,BDCSURCO0000000009610631,Commune simple,40046,Biscarrosse,2,LANDES,40,NOUVELLE-AQUITAINE,75,244000873,BISCARROSSE,14174,"POLYGON ((365687 6369053, 363847 6369010, 3611..."
926,BDCSURCO0000000009610974,Commune simple,40257,Sainte-Eulalie-en-Born,2,LANDES,40,NOUVELLE-AQUITAINE,75,244000873,SAINTE-EULALIE-EN-BORN,1279,"POLYGON ((357950 6361699, 357994 6361911, 3580..."
927,BDCSURCO0000000009610449,Commune simple,40287,Sanguinet,2,LANDES,40,NOUVELLE-AQUITAINE,75,244000873,SANGUINET,3655,"POLYGON ((379327 6377499, 376082 6379415, 3760..."
928,BDCSURCO0000000009610799,Commune simple,40217,Parentis-en-Born,2,LANDES,40,NOUVELLE-AQUITAINE,75,244000873,PARENTIS-EN-BORN,5772,"POLYGON ((370045 6362405, 370081 6362553, 3701..."

In [48]:
import pandas as pd
import json
import requests
import geopandas as gpd

communes_littorales = gpd.read_file("../data/communes_littorales/communes_littorales.shp")
communes_littorales['INSEE_COM'] = communes_littorales['INSEE_COM'].astype(str).str.zfill(5)

df_total = pd.DataFrame()
for dep in communes_littorales['INSEE_DEP'].unique():
    print(dep, len(communes_littorales[communes_littorales['INSEE_DEP'] == dep]))
    comm_list = communes_littorales[communes_littorales['INSEE_DEP'] == dep]['INSEE_COM'].tolist()


    # Construction de l'URL avec toutes les communes de comm_list
    geo_params = "&".join([f"GEO=COM-{code}" for code in comm_list])
    api_url = f"https://api.insee.fr/melodi/V2/data/DS_FILOSOFI_CC?{geo_params}&FILOSOFI_MEASURE=IR_D9_D1_SL"


    get_data = requests.get(api_url, verify= False)
    data_from_net = get_data.content
    try:
        data = json.loads(data_from_net)
    except:
        continue
    # Extraction des informations du jeu de données
    title = data['title']['fr']
    identifier = data['identifier']

    #Extraction des observations du jeu de données filtré, sur lesquelles on va boucler
    observations = data['observations']
    extracted_data = []

    #Boucle de lecture des observations dans le json 
    for obs in observations:
        dimensions = obs['dimensions']
        
        # Suivant les jeux de données attributes est présent ou non
        if 'attributes' in obs:
            attributes = obs['attributes']
        else:
            attributes = None

        # Suivant les jeux de données value peut être absent
        if 'value' in obs['measures']['OBS_VALUE_NIVEAU']:
            measures = obs['measures']['OBS_VALUE_NIVEAU']['value']
        else:
            mesures = None
        
        # on rassemble tout dans un objet
        if 'attributes' in obs:
            combined_data = {**dimensions,**attributes, 'OBS_VALUE_NIVEAU': measures}
        else:
            combined_data = {**dimensions, 'OBS_VALUE_NIVEAU': measures}
        
        extracted_data.append(combined_data)

    #Création d'un dataframe python
    df = pd.DataFrame(extracted_data)
    df_total = pd.concat([df_total, df], ignore_index=True)

    # print(f'Jeu de données : {identifier} \nTitre : {title} ')
    print('Loaded', len(df), 'rows for dep', dep)

56 64

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Loaded 64 rows for dep 56
13 22
Loaded 22 rows for dep 13
2A 33

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Loaded 33 rows for dep 2A
2B 65
Loaded 65 rows for dep 2B
17 72

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

33 38
Loaded 38 rows for dep 33
85 31

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

76 46
Loaded 46 rows for dep 76
29 116

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Loaded 116 rows for dep 29
22 64
66 15

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Loaded 15 rows for dep 66
34 26
Loaded 26 rows for dep 34
44 28

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Loaded 28 rows for dep 44
59 9
Loaded 9 rows for dep 59
62 29

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Loaded 29 rows for dep 62
11 10
Loaded 10 rows for dep 11
83 27

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Loaded 27 rows for dep 83
35 21
Loaded 21 rows for dep 35
14 54

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Loaded 54 rows for dep 14
06 16
Loaded 16 rows for dep 06
50 86

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

27 8
Loaded 8 rows for dep 27
80 16

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Loaded 16 rows for dep 80
30 4
Loaded 4 rows for dep 30
40 19

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Loaded 19 rows for dep 40
64 10
Loaded 10 rows for dep 64

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [51]:
df_total.shape, communes_littorales.shape

((676, 8), (929, 13))

In [53]:
df_total

,GEO,TIME_PERIOD,UNIT_MEASURE,FILOSOFI_MEASURE,OBS_STATUS,UNIT_MULT,CONF_STATUS,OBS_VALUE_NIVEAU
0,2025-COM-56054,2021,_Z,IR_D9_D1_SL,A,0,F,2.8
1,2025-COM-56234,2021,_Z,IR_D9_D1_SL,A,0,F,3.1
2,2025-COM-56007,2021,_Z,IR_D9_D1_SL,A,0,F,3.2
3,2025-COM-56008,2021,_Z,IR_D9_D1_SL,A,0,F,3.5
4,2025-COM-56098,2021,_Z,IR_D9_D1_SL,A,0,F,2.7
...,...,...,...,...,...,...,...,...
671,2025-COM-64125,2021,_Z,IR_D9_D1_SL,A,0,F,3.6
672,2025-COM-64545,2021,_Z,IR_D9_D1_SL,A,0,F,2.9
673,2025-COM-64483,2021,_Z,IR_D9_D1_SL,A,0,F,3.5
674,2025-COM-64249,2021,_Z,IR_D9_D1_SL,A,0,C,3.5
675,2025-COM-64102,2021,_Z,IR_D9_D1_SL,A,0,F,3.2

{'17', '50', '85'}

In [67]:
from math import ceil

dep = 17
communes_dep = communes_littorales[communes_littorales['INSEE_DEP'] == str(dep).zfill(2)]['INSEE_COM'].tolist()
missing_communes = [com for com in communes_dep if com not in df_total['GEO'].str.split('-').str[-1].tolist()]


batch_size = 8
num_batches = ceil(len(missing_communes) / batch_size)

for i in range(num_batches):
    batch = missing_communes[i*batch_size:(i+1)*batch_size]
    if not batch:
        continue
    geo_params = "&".join([f"GEO=COM-{com}" for com in batch])
    url_api = f"https://api.insee.fr/melodi/V2/data/DS_FILOSOFI_CC?{geo_params}&FILOSOFI_MEASURE=IR_D9_D1_SL"
    print(f"Batch {i+1}/{num_batches}: {batch}")
    get_data = requests.get(url_api, verify=False)
    data_from_net = get_data.content
    try:
        data = json.loads(data_from_net)
    except:
        print("Failed to load data for batch:", batch)
        continue
    if 'observations' not in data:
        print("No observations for batch:", batch)
        continue
    observations = data['observations']
    extracted_data = []
    for obs in observations:
        dimensions = obs['dimensions']
        attributes = obs.get('attributes', None)
        if 'value' in obs['measures']['OBS_VALUE_NIVEAU']:
            measures = obs['measures']['OBS_VALUE_NIVEAU']['value']
        else:
            measures = None
        if attributes:
            combined_data = {**dimensions, **attributes, 'OBS_VALUE_NIVEAU': measures}
        else:
            combined_data = {**dimensions, 'OBS_VALUE_NIVEAU': measures}
        extracted_data.append(combined_data)
    if extracted_data:
        df = pd.DataFrame(extracted_data)
        df_total = pd.concat([df_total, df], ignore_index=True)

Batch 1/9: ['17328', '17325', '17410', '17405', '17034', '17160', '17015', '17248']
Batch 2/9: ['17098', '17437', '17346', '17449', '17151', '17411', '17375', '17485']

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\colin\AppData\Local\Temp\ipykernel_90848\686164631.py:44: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_total = pd.concat([df_total, df], ignore_index=True)
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Batch 3/9: ['17484', '17219', '17353', '17452', '17385', '17140', '17064', '17021']
Batch 4/9: ['17189', '17058', '17351', '17265', '17329', '17093', '17337', '17461']

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Failed to load data for batch: ['17189', '17058', '17351', '17265', '17329', '17093', '17337', '17461']
Batch 5/9: ['17168', '17429', '17421', '17299', '17463', '17185', '17146', '17380']
Batch 6/9: ['17333', '17306', '17230', '17237', '17079', '17409', '17225', '17155']

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Batch 7/9: ['17247', '17019', '17318', '17094', '17190', '17004', '17264', '17010']
Batch 8/9: ['17369', '17297', '17091', '17161', '17486', '17323', '17360', '17028']

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Batch 9/9: ['17300', '17483', '17121', '17051', '17222', '17286', '17153', '17207']

c:\Users\colin\anaconda3\envs\xr_app\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.insee.fr'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [61]:
df_total['CODGEO'] = df_total['GEO'].str.split('-').str[-1]

In [68]:
print(set(communes_littorales['INSEE_COM'].tolist()) - set(df_total['CODGEO'].tolist()))
print(len(set(communes_littorales['INSEE_COM'].tolist()) - set(df_total['CODGEO'].tolist())), "missing communes")

{'85049', '50585', '17094', '17064', '50342', '50160', '17486', '22253', '50218', '17369', '50199', '17247', '85255', '50403', '50496', '85164', '17323', '50429', '85106', '85004', '50433', '17010', '50081', '50041', '22379', '22363', '85243', '50031', '50509', '50442', '50507', '50636', '85267', '50143', '50190', '85083', '50085', '50421', '85294', '50231', '50332', '17485', '17300', '50015', '50532', '17297', '17484', '50353', '50033', '17463', '85288', '17168', '50268', '50243', '50021', '17160', '85234', '50196', '85127', '50078', '50066', '50408', '50349', '50117', '17185', '85011', '50296', '50503', '17121', '50388', '50471', '50490', '17405', '50427', '17409', '50410', '17140', '50604', '50102', '50215', '17161', '17151', '17286', '50288', '17265', '50150', '50042', '50108', '17325', '85035', '17410', '50184', '50412', '50267', '17153', '50612', '85001', '17351', '17004', '50025', '50253', '17306', '50543', '50272', '17437', '22242', '17375', '85104', '22154', '17328', '17155', '50562', '22173', '50129', '50089', '17034', '50030', '85088', '50151', '17429', '85307', '17146', '17098', '17452', '17207', '50003', '17015', '85297', '17380', '17461', '17222', '17329', '17421', '85185', '50238', '50077', '17346', '17219', '85114', '17091', '17051', '17021', '17411', '17190', '50014', '85112', '17237', '17230', '50481', '50407', '50616', '85278', '50603', '50162', '17333', '17019', '85222', '50402', '17449', '50022', '85012', '17264', '17028', '17299', '85226', '85113', '50358', '17248', '17360', '85029', '17318', '50076', '17337', '22209', '17079', '50165', '50576', '85163', '50479', '50058', '17385', '50178', '17225', '50198', '50146', '50417', '50167', '17093', '22350', '85018', '17353', '17189', '85194', '17058', '17483', '50142', '50517'}
197 missing communes

In [41]:
api_url

'https://api.insee.fr/melodi/V2/data/DS_FILOSOFI_CC?GEO=COM-11170&FILOSOFI_MEASURE=IR_D9_D1_SL'

In [19]:
df

,GEO,TIME_PERIOD,UNIT_MEASURE,FILOSOFI_MEASURE,OBS_STATUS,UNIT_MULT,CONF_STATUS,OBS_VALUE_NIVEAU
0,2025-COM-01001,2021,_Z,IR_D9_D1_SL,A,0,C,3.6
1,2025-COM-34199,2021,_Z,IR_D9_D1_SL,A,0,F,3.6

In [105]:
path = '../../Data/INSEE/DS_FILOSOFI_CC_2021_CSV_FR/DS_FILOSOFI_CC_2021_data.csv'
df_filo = pd.read_csv(path, sep=';')
df_filo = df_filo[df_filo.FILOSOFI_MEASURE == 'IR_D9_D1_SL']
df_filo_comm = df_filo[df_filo.GEO_OBJECT == 'COM']
df_filo_epci = df_filo[df_filo.GEO_OBJECT == 'EPCI']
df_filo_comm['CODGEO'] = df_filo_comm['GEO']
df_filo_comm = communes_littorales[['INSEE_COM', 'CODE_EPCI']].merge(df_filo_comm[['CODGEO', 'OBS_VALUE']], left_on='INSEE_COM', right_on='CODGEO', how='left')
df_filo_comm.loc[df_filo_comm['CODGEO'].isna(), 'level'] = 'EPCI'
df_filo_comm.loc[df_filo_comm['CODGEO'].notna(), 'level'] = 'COM'
#for the nan value merge with the epci value
df_filo_comm.loc[df_filo_comm['OBS_VALUE'].isna(), 'OBS_VALUE'] = df_filo_comm.CODE_EPCI.map(df_filo_epci.set_index('GEO')['OBS_VALUE'])
df_filo_comm.drop(columns=['CODGEO', 'CODE_EPCI'], inplace=True)

C:\Users\colin\AppData\Local\Temp\ipykernel_90848\1804061267.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_filo = pd.read_csv(path, sep=';')
C:\Users\colin\AppData\Local\Temp\ipykernel_90848\1804061267.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filo_comm['CODGEO'] = df_filo_comm['GEO']

In [106]:
df_filo_comm

    INSEE_COM  OBS_VALUE level
0       56084        3.1  EPCI
1       56262        3.1  EPCI
2       56069        2.9  EPCI
3       56248        3.1  EPCI
4       56260        3.1  EPCI
..        ...        ...   ...
924     40108        2.7   COM
925     40046        2.9   COM
926     40257        2.7   COM
927     40287        2.7   COM
928     40217        2.4   COM

[929 rows x 3 columns]

In [100]:
path = '../../Data/INSEE/DS_FILOSOFI_CC_2021_CSV_FR/DS_FILOSOFI_CC_2021_data.csv'
df_filo = pd.read_csv(path, sep=';')
df_filo = df_filo[df_filo.FILOSOFI_MEASURE == 'IR_D9_D1_SL']
df_filo_comm = df_filo[df_filo.GEO_OBJECT == 'COM']
df_filo_epci = df_filo[df_filo.GEO_OBJECT == 'EPCI']
df_filo_comm['CODGEO'] = df_filo_comm['GEO']
# Remove rows where 'CODGEO' is NA before filtering
df_filo_comm[df_filo_comm['CODGEO'].notna() & df_filo_comm['CODGEO'].str.startswith('22')]
# df_filo_comm[df_filo_comm['CODGEO'].isna()]

C:\Users\colin\AppData\Local\Temp\ipykernel_90848\43325999.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_filo = pd.read_csv(path, sep=';')
C:\Users\colin\AppData\Local\Temp\ipykernel_90848\43325999.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filo_comm['CODGEO'] = df_filo_comm['GEO']

,GEO,GEO_OBJECT,FILOSOFI_MEASURE,UNIT_MEASURE,UNIT_MULT,CONF_STATUS,OBS_STATUS,TIME_PERIOD,OBS_VALUE,CODGEO
11306,22337,COM,IR_D9_D1_SL,_Z,0,C,A,2021,NaN,22337
11604,22194,COM,IR_D9_D1_SL,_Z,0,F,A,2021,2.7,22194
11664,22039,COM,IR_D9_D1_SL,_Z,0,C,A,2021,NaN,22039
11671,22326,COM,IR_D9_D1_SL,_Z,0,C,A,2021,NaN,22326
11691,22111,COM,IR_D9_D1_SL,_Z,0,C,A,2021,NaN,22111
...,...,...,...,...,...,...,...,...,...,...
74363,22215,COM,IR_D9_D1_SL,_Z,0,F,A,2021,2.7,22215
74399,22331,COM,IR_D9_D1_SL,_Z,0,C,A,2021,NaN,22331
74425,22156,COM,IR_D9_D1_SL,_Z,0,C,A,2021,NaN,22156
74434,22086,COM,IR_D9_D1_SL,_Z,0,C,A,2021,NaN,22086
74550,22320,COM,IR_D9_D1_SL,_Z,0,C,A,2021,NaN,22320

In [83]:
df = pd.read_csv(path, sep=';')
df = df[df.FILOSOFI_MEASURE == 'IR_D9_D1_SL']
df = df[df.GEO_OBJECT=='EPCI']
# df[df.GEO=='50585']
df.OBS_VALUE.isna().sum()

C:\Users\colin\AppData\Local\Temp\ipykernel_90848\342554417.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep=';')

np.int64(0)

In [84]:
df.GEO

758449    200035087
758567    200071454
758639    200070514
758640    200070316
758700    200065928
            ...
790258    249100553
790265    248400236
790281    247000011
790343    245300447
790387    242600534
Name: GEO, Length: 1240, dtype: object